//Write a program to print all employee names?
let employees=[{"eid":1,"ename":"Brynne","gender":"Female"},
{"eid":2,"ename":"Eustace","gender":"Male"},
{"eid":3,"ename":"Myriam","gender":"Female"},
{"eid":4,"ename":"Albie","gender":"Male"},
{"eid":5,"ename":"Yorker","gender":"Male"},
{"eid":6,"ename":"Brittney","gender":"Female"},
{"eid":7,"ename":"Jolee","gender":"Female"},
{"eid":8,"ename":"Conant","gender":"Male"},
{"eid":9,"ename":"Reid","gender":"Male"},
{"eid":10,"ename":"Corabelle","gender":"Female"},
{"eid":11,"ename":"Alina","gender":"Female"},
{"eid":12,"ename":"Jobey","gender":"Female"},
{"eid":13,"ename":"Kassia","gender":"Female"},
{"eid":14,"ename":"Alyda","gender":"Female"},
{"eid":15,"ename":"Rodrique","gender":"Male"},
{"eid":16,"ename":"Marika","gender":"Female"},
{"eid":17,"ename":"Nada","gender":"Female"},
{"eid":18,"ename":"Kiersten","gender":"Female"},
{"eid":19,"ename":"Claudian","gender":"Male"},
{"eid":20,"ename":"Elihu","gender":"Male"},
{"eid":21,"ename":"Raymund","gender":"Male"},
{"eid":22,"ename":"Iosep","gender":"Male"},
{"eid":23,"ename":"Elysia","gender":"Female"},
{"eid":24,"ename":"Phillida","gender":"Female"},
{"eid":25,"ename":"Bernhard","gender":"Male"},
{"eid":26,"ename":"Cori","gender":"Male"},
{"eid":27,"ename":"Clyde","gender":"Male"},
{"eid":28,"ename":"Charis","gender":"Female"},
{"eid":29,"ename":"Natalee","gender":"Female"},
{"eid":30,"ename":"Ernestus","gender":"Male"},
{"eid":31,"ename":"Barret","gender":"Male"},
{"eid":32,"ename":"Billy","gender":"Female"},
{"eid":33,"ename":"Patty","gender":"Female"},
{"eid":34,"ename":"Mitchell","gender":"Male"},
{"eid":35,"ename":"Roman","gender":"Male"},
{"eid":36,"ename":"Tabbie","gender":"Male"},
{"eid":37,"ename":"Shell","gender":"Female"},
{"eid":38,"ename":"Meridel","gender":"Female"},
{"eid":39,"ename":"Edan","gender":"Male"},
{"eid":40,"ename":"Mandy","gender":"Female"},
{"eid":41,"ename":"Erinn","gender":"Female"},
{"eid":42,"ename":"Jandy","gender":"Female"},
{"eid":43,"ename":"Lenci","gender":"Male"},
{"eid":44,"ename":"Sauveur","gender":"Male"},
{"eid":45,"ename":"Cindelyn","gender":"Female"},
{"eid":46,"ename":"Birk","gender":"Male"},
{"eid":47,"ename":"Adele","gender":"Female"},
{"eid":48,"ename":"Erek","gender":"Male"},
{"eid":49,"ename":"Caresse","gender":"Female"},
{"eid":50,"ename":"Noni","gender":"Female"},
{"eid":51,"ename":"Rosemonde","gender":"Female"},
{"eid":52,"ename":"Loren","gender":"Male"},
{"eid":53,"ename":"Pru","gender":"Female"},
{"eid":54,"ename":"Randy","gender":"Male"},
{"eid":55,"ename":"Myrtie","gender":"Female"},
{"eid":56,"ename":"Jerrie","gender":"Female"},
{"eid":57,"ename":"Quincy","gender":"Male"},
{"eid":58,"ename":"Papagena","gender":"Female"},
{"eid":59,"ename":"Leonerd","gender":"Male"},
{"eid":60,"ename":"Lucky","gender":"Female"},
{"eid":61,"ename":"Sacha","gender":"Female"},
{"eid":62,"ename":"Dael","gender":"Female"},
{"eid":63,"ename":"Mandie","gender":"Female"},
{"eid":64,"ename":"Vaughn","gender":"Male"},
{"eid":65,"ename":"Carly","gender":"Male"},
{"eid":66,"ename":"Shirley","gender":"Female"},
{"eid":67,"ename":"Lewiss","gender":"Male"},
{"eid":68,"ename":"Clemmy","gender":"Male"},
{"eid":69,"ename":"Sheffy","gender":"Male"},
{"eid":70,"ename":"Analise","gender":"Female"},
{"eid":71,"ename":"Wash","gender":"Male"},
{"eid":72,"ename":"Torey","gender":"Female"},
{"eid":73,"ename":"Petronilla","gender":"Female"},
{"eid":74,"ename":"Marlon","gender":"Male"},
{"eid":75,"ename":"Elisabeth","gender":"Female"},
{"eid":76,"ename":"Tilly","gender":"Female"},
{"eid":77,"ename":"Nathanial","gender":"Male"},
{"eid":78,"ename":"Benedick","gender":"Male"},
{"eid":79,"ename":"Hill","gender":"Male"},
{"eid":80,"ename":"Cissy","gender":"Female"},
{"eid":81,"ename":"Reed","gender":"Male"},
{"eid":82,"ename":"Andre","gender":"Male"},
{"eid":83,"ename":"Darwin","gender":"Male"},
{"eid":84,"ename":"Isidora","gender":"Female"},
{"eid":85,"ename":"Bonita","gender":"Female"},
{"eid":86,"ename":"Murdoch","gender":"Male"},
{"eid":87,"ename":"Inglis","gender":"Male"},
{"eid":88,"ename":"Nikaniki","gender":"Female"},
{"eid":89,"ename":"Pete","gender":"Male"},
{"eid":90,"ename":"Filippo","gender":"Male"},
{"eid":91,"ename":"Patty","gender":"Male"},
{"eid":92,"ename":"Shirlene","gender":"Female"},
{"eid":93,"ename":"Vallie","gender":"Female"},
{"eid":94,"ename":"Jozef","gender":"Male"},
{"eid":95,"ename":"Willyt","gender":"Female"},
{"eid":96,"ename":"Normy","gender":"Male"},
{"eid":97,"ename":"Lenee","gender":"Female"},
{"eid":98,"ename":"Townie","gender":"Male"},
{"eid":99,"ename":"Thornie","gender":"Male"},
{"eid":100,"ename":"Arabella","gender":"Female"}]


// for(let emp of employees)
// {
//     console.log(emp.ename)
// }

for(let emp of employees)
{
    console.log(`Name:${emp.ename} and Gender:${emp.gender}`)
}